//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> ServicesId { get; set; }
        public Nullable<int> UsersId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> Adminid { get; set; }
        public System.DateTime ДатаЗаписи { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
    }
}
